### ISSUE TITLE
Export C++ created from translation

### ISSUE THREAD

**Issue by coatless** [dirkschumacher/armacmp#1]
I think this is an interesting experiment and a good learning tool for someone use to understand translating code between _R_ and _C++_. That said, the generated _C++_ syntax is largely hidden. 

I think it might be helpful to surface with albeit better name the `compile_to_str()` function.

https://github.com/dirkschumacher/armacmp/blob/5fa59f39015220005c9a5bc9e0fa8c91e14a7f4b/R/compiler.R#L1

**Comment by dirkschumacher** [comment]
Yeah sounds like a good idea.👍

**Comment by dirkschumacher** [comment]
First prototype:

``` r
armacmp_compile(function(new_X, coef = type_colvec()) {
  res <- new_X %*% coef
  score <- 1 / (1 + exp(-res))
  return(X_new)
}, "log_predict")
#> Compiled R function
#> 
#> function (new_X, coef = type_colvec()) 
#> {
#>     res <- new_X %*% coef
#>     score <- 1/(1 + exp(-res))
#>     return(X_new)
#> }
#> 
#> =>
#> 
#> arma::mat log_predict(const arma::mat& new_X, const arma::colvec& coef)
#> {
#> arma::mat res = new_X * coef;
#> arma::mat score = 1 / ( 1 + arma::exp( -res ) );
#> return X_new;
#> }
#> 
```

**Comment by coatless** [comment]
Awesome!

Two minor knits, add a section header for the C++ code e.g.

> C++ function translation

Consider also adding a `verbose = TRUE` option to the original `armacmp()` function to show the output.

**Comment by dirkschumacher** [comment]
``` r
armacmp::armacmp(function(X) {
  return(colSums(X))
}, verbose = TRUE)
#> R function
#> 
#> function (X) 
#> {
#>     return(colSums(X))
#> }
#> 
#> C++ function translation
#> 
#> arma::mat armacmp_fun(const arma::mat& X)
#> {
#> return arma::sum( X, 0 );
#> }
#> function (X) 
#> .Call(<pointer: 0x1111fefc0>, X)
#> <environment: 0x7ffbd2bc8288>
```

<sup>Created on 2019-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
