### ISSUE TITLE
Lambdas?

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#16]
```R
armacmp(function(X) {
  fun <- function(y = type_scalar_numeric()) {
    return(X + log(y))
  }
  return(fun(20))
})
```
Could be translated to C++14 lambdas with `auto` return type.

**Comment by coatless** [comment]
Eh, we only now have support for C++11 and even then the majority of base R packages are written in C++98. So, I'd hold off on anything using a higher standard. :/

**Comment by eddelbuettel** [comment]
There are packages requiring C++14 on CRAN, xtensor is an example.

Typo in the Subject though -- I also often drop the b in lamBda.   :grinning:

**Comment by dirkschumacher** [comment]
But why is it a problem to release a package with C++14? Is it that that so few people have compiler support for it?

**Comment by eddelbuettel** [comment]
I didn't say it was a problem.  See Writing R Extensions, as usual, for the gory details.

On Windoze we (for now, for a while, for ...) stlll at g++ 4.9.4 where support is complete / missing.  Just google / search.   But contrary to what James said above, it is not a rejection criterion for CRAN.  

You can impose other C++ standard _in your C++ code_.  I added a plugin for C++20 before it was finalized -- CRAN does test with g++-9 after all.  But such packages may not build for all R users as some use RH or other old releases with g++-4.4 which still uses punch cards (I am kidding but you get the drift).

So for wide use assume tools conservatively.  If needed and more restricted deployment is the price of admission, C++14 or even C++17 may work.  There is some cool SIMD work coming that requires C++17.  One if Jeroen succeeds we will g++-8 on Windows too "at some point" and can use it. 

But ignore all I said. I just suggested to fix a typo ;-)

**Comment by dirkschumacher** [comment]
Thanks for long explanation👍

**Comment by dirkschumacher** [comment]
Note to future me: So using the `auto_or_arma::™️` type deduction system, it is possible without C++14 AFAIK as captured variables are defined without a type and C++11 also has the same auto return type deduction mechanism as C++14 for lambdas "deduced as if for C++14 auto-returning function" [1](https://en.cppreference.com/w/cpp/language/lambda).

**Comment by conradsnicta** [comment]
@dirkschumacher Side note: please don't use the `auto` type declaration with armadillo objects and expressions. `auto` doesn't handle expression templates well, which are extensively used by armadillo.

**Comment by dirkschumacher** [comment]
thanks @conradsnicta. I try to only use `auto` for non arma types (e.g. scalars). Does that cause problems as well?

**Comment by dirkschumacher** [comment]
Working now with PR #41 - at least for some test cases 🙈
``` r
library(armacmp)
fun <- armacmp(function(X) {
  fun <- function(y = type_scalar_numeric()) {
    return(X + log(y))
  }
  return(fun(20))
})
fun(matrix(1:10))
#>            [,1]
#>  [1,]  3.995732
#>  [2,]  4.995732
#>  [3,]  5.995732
#>  [4,]  6.995732
#>  [5,]  7.995732
#>  [6,]  8.995732
#>  [7,]  9.995732
#>  [8,] 10.995732
#>  [9,] 11.995732
#> [10,] 12.995732
```

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by conradsnicta** [comment]
@dirkschumacher 
 > I try to only use auto for non arma types (e.g. scalars). Does that cause problems as well?

Scalars shouldn't be a problem.  For example, `scalar = mean(v)` where `v` is explicitly declared as a vector (eg. `vec`, `colvec`, `rowvec`) or a submatrix column / row (eg. `X.col(123)`, `X.row(123`), or the result of an expression which results in a vector (eg. `v = mean(A)`, where `A` is a matrix).

For paranoia, you can always wrap an expression in `scalar = as_scalar(expression)`.  It has no performance degradation if `expression` is already a scalar. The resultant code won't look as pretty, but it may simplify things in the transpiler.
