### ISSUE TITLE
Format C++ code

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#2]
Is there a good option to format the generated C++ code so it looks nice?

**Comment by coatless** [comment]
Unfortunately, I think a system dependency would be required (c.f. [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html)) as the present formatters ([`formatR`](https://github.com/yihui/formatR), [`styler`](https://github.com/r-lib/styler), [`highlight`](https://github.com/romainfrancois/highlight)) are _R_-focused.

**Comment by coatless** [comment]
Thinking about this more as this is a translation of a unit... Couldn't the _R_ code be formatted initially and, then, just do in place substitution with the C++ phrases to avoid needing to manage C++ format?

**Comment by dirkschumacher** [comment]
Thanks. Yeah that might work.

**Comment by dirkschumacher** [comment]
See #11 for further discussion
