### ISSUE TITLE
Control compilation

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#22]
Like `-O2` or `-O3` or if `openmp` is used, MKL or OpenBLAS etc.

http://arma.sourceforge.net/faq.html#speed

**Comment by coatless** [comment]
Automatically handled by `Makevars`, c.f. `Sys.setenv()`.

**Comment by dirkschumacher** [comment]
Ok. Then I need to document that (and before try it :))

**Comment by coatless** [comment]
By default OpenMP is on (outside of macOS) for armadillo. This is set via a plugin manager on package install for RcppArmadillo. Since the compilation happens under `sourceCpp()` everything is "okay"

**Comment by dirkschumacher** [comment]
So I understand that an expert user would simply consult the Rcpp and Armadillo docs and sets environment variables/configures BLAS as necessary outside of this package
