### ISSUE TITLE
Generate random variables names based on input code

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#27]
Note to self: For for loops I need random variable names. At the moment the change everytime `armacmp` is invoked. Ideally the pseudo-random names should depend on the code of the input function. If the function does not change, then the var names should stay the same.

**Comment by coatless** [comment]
Consider using [`uuid`](https://CRAN.R-project.org/package=uuid) or [`digest`](https://CRAN.R-project.org/package=digest).
