### ISSUE TITLE
Add `svd`

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#3]

**Comment by coatless** [comment]
I think [svd](http://arma.sourceforge.net/docs.html#svd) could mirror how [QR](http://arma.sourceforge.net/docs.html#qr) is setup.

```cpp
## QR 
mat X = randu<mat>(5,5);
mat Q, R;

qr(Q,R,X);

## SVD
mat X = randu<mat>(5,5);

mat U, V;
vec s;

svd(U, s, V, X);
```

Though, the parser right now seems to require a better way to processes statements, c.f.

https://github.com/dirkschumacher/armacmp/blob/1c3041e5edad677e5d4ed7c8029998c55cf69b99/R/compiler.R#L53-L64

**Comment by dirkschumacher** [comment]
Yeah it needs to be a bit more modular and nicer. But I thought the "assignment" node can decide how to format itself if the right hand side is QR or svd. This does not work anymore if there are more, but for now ... :)

But in R `svd` does not have these nice accessor functions like `QR`.

**Comment by dirkschumacher** [comment]
Note to self: this might be a bit more tricky, as in R you write code like this:
```R
(s <- svd(X))
D <- diag(s$d)
s$u
```
That means I have to track which name refers to the svd call. The problem is that since we now have for loops and if/else statements, we also need to keep track of the scope of variables which I do not want to do as long as possible :)

**Comment by dirkschumacher** [comment]
Note to self and thinking out loud: the `$` operator class could ask the left-hand-side for the value of the name and then pass the right-hand-side expression to a special compile method.
