### ISSUE TITLE
Add min/max

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#34]

**Comment by dirkschumacher** [comment]
Similiar to how `sum` is implemented I believe. Depends a bit on the docs. I would suggest just implementing the version that reduces the result to a single number.

https://github.com/dirkschumacher/armacmp/blob/5777a3f393ee3c9aebd42bc29324eaecc5f3859c/R/ast-classes.R#L1477-L1490

**Comment by dselivanov** [comment]
This is extremely useful. It is impossible to write many algorithms without `min/max/colmin/colmax/rowmin/rowmax`

**Comment by dirkschumacher** [comment]
Since there is no `colmin/rowmin` in R, I just implemented `min/max` for now.
