### ISSUE TITLE
Integer like numerics should be compiled to doubles with trailing `.0`

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#36]
```
2 => 2.0
2.1 => 2.1
-3 => -3.0
```

From the docs of `sprintf` "Numeric variables with exactly integer values will be coerced to integer."

**Comment by coatless** [comment]
I would be careful about this during _equality checks_. For instance, the comparison in a loop condition is better with an `int` than a `double`.
