### ISSUE TITLE
Rename functions

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#40]
What could be good names for the three main functions?

* `armacmp` translates a function to C++, compiles it and creates an R function for you
* `armacmp_compile` translates a function to C++
* `arma_optim` compiles your optimization problem to C++ and contructs an R function for you.

Package name candidates:
* armacmp
* armacompile
* translator
* trcpp
* r2cpp
* babel (probably bad due to existing names)
* linearbabel
* babelarmadillo
* babelr
* ... to be extended

**Comment by coatless** [comment]
Probably a better package name is needed. From there the function names can correspond.... 

- translator
- trcpp
- r2cpp
- babel (probably bad due to existing names)

**Comment by dirkschumacher** [comment]
Thanks. Yeah the package name could also be changed. But I would like to keep it tied to armadillo and ensmallen, so it does not evolve into a general purpose R to C++ transpiler :)

**Comment by dirkschumacher** [comment]
For functions maybe:
* `compile` does the whole thing R -> C++ -> R
* `translate` generates the C++ text representation
* `compile_optimization_problem` compiles an optimization problem using ensmallen

**Comment by dirkschumacher** [comment]
I think I leave it as it is (after 51b3d47) for now
