### ISSUE TITLE
Support i:j syntax for contructing integer sequences

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#44]

**Comment by dirkschumacher** [comment]
`seq`, `seq_len` and `a:b` create double vectors as opposed to integer vectors in R. But it would be nice to keep things double for now within C++. Not sure if that is a good idea.

**Comment by coatless** [comment]
@dirkschumacher not completely.

```
class(1:4)
# [1] "integer"

class(1.1:4.1)
# [1] "numeric"

class(1L:4L)
# [1] "integer"
```

I think `arma::linspace<arma::ivec>()` for integer and `arma::linspace<arma::vec>()` for double.

**Comment by dirkschumacher** [comment]
Yeah maybe it should depend on the type of the input var.

By the way: the docs say that `vec` is just an alias for `colvec` (this is how I read it at least). Is there any problem with using only `colvec` instead of `vec`?

**Comment by coatless** [comment]
@dirkschumacher no problem. `colvec` just has 3 more characters than `vec`. So, I usually opted for that as I knew what the orientation would be.

**Comment by dirkschumacher** [comment]
Yeah I thought I makes it clearer that this is a column vector. OK. Then I will leave the `colvec`. Thanks!

**Comment by dirkschumacher** [comment]
Created a new issue for input type dependent output types #47
