### ISSUE TITLE
Make input vars of main function values instead of const refs

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#45]
I think this should be possible without an extra variable. It is also possible to detect that automatically and then make the input var not a reference.

```R
function(X) {
  X <- X + 10
  return(X)
}
```

**Comment by coatless** [comment]
How about `const arma::T&` if and only if nothing is detected. Otherwise, copy the data `arma::T`. I think this would be the safest way forward. 

Reusing memory via armadillo's advanced ctor would modify the _R_ object and be undesirable cause of confusion. 

That is:

```cpp
#include<RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
void ref_update(arma::vec& x) {
    x += 10;
}
```

```r
(x = 1.1:5.1)
# [1] 1.1 2.1 3.1 4.1 5.1

ref_update(x)

x
# [1] 11.1 12.1 13.1 14.1 15.1
```

**Comment by dirkschumacher** [comment]
Thanks. I think this is the way to go

**Comment by dirkschumacher** [comment]
Note to self: currently I only know during the compile step if a variable is reassigned. But then the code has already emitted for the initial assignment. So there needs to be another mechanism that works on the AST before the compilation step (which is good).

Once this is implemented, I could add `constexpr` to scalar assignments that are not reassigned.

**Comment by dirkschumacher** [comment]
Checked the assembly code of some simple examples: I think it does not matter to add `constexpr` to any simple scalar assignment.

**Comment by dirkschumacher** [comment]
``` r
fun <- armacmp::armacmp(function(X) {
  X <- X + 10
  return(X)
}, verbose = TRUE)
#> R function
#> 
#> function (X) 
#> {
#>     X <- X + 10
#>     return(X)
#> }
#> 
#> C++ function translation
#> 
#> arma::mat armacmp_fun(arma::mat X)
#> {
#> X = X + 10.0;
#> return X;
#> }
```

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
