### ISSUE TITLE
Add documentation comparing supported R <-> arma functions

### ISSUE THREAD

**Issue by dirkschumacher** [dirkschumacher/armacmp#6]
A huge list with sample code showing all supported functions. As a vignette ideally.

**Comment by coatless** [comment]
Few remarks upon reading through the vignette:

- Any reason for the `=` vs. `<-` difference? Isn't the LHS variable tracked under the AST? I'm willing to bet more folks in _R_ use `<-` throughout whereas more in Cpp land use `=`. 
- Potentially add a note regarding how to see the translated C++?  
- The `if`/`else if`/`else` with `return` statements under each condition is a bit odd. How about having them create a matrix prior to the computation and a single return at the end?

**Comment by dirkschumacher** [comment]
Thanks!
 
>     * Any reason for the `=` vs. `<-` difference? Isn't the LHS variable tracked under the AST? I'm willing to bet more folks in _R_ use `<-` throughout whereas more in Cpp land use `=`.

The only current reason is that the "data structure" of my annotated AST is really just a badly structured list of lists with no way traversing the tree upwards. Once this is possible, then one can check if a variable is already in scope or not. Also I can then implement the `svd` function. I thought with the `=` operator it is still valid R code and there is a way to distinguish between assignment and reassignment.

>     * Potentially add a note regarding how to see the translated C++?
Yeah. That's a good idea.

>     * The `if`/`else if`/`else` with `return` statements under each condition is a bit odd. How about having them create a matrix prior to the computation and a single return at the end?
Do you mean multiple returns in general or just the structure of the example?

**Comment by coatless** [comment]
>  I thought with the = operator it is still valid R code and there is a way to distinguish between assignment and reassignment.

It is. But, the current style guides will encourage one use over another. It's also a bit more "fragile" for someone new to _C++_.

> Do you mean multiple returns in general or just the structure of the example?

Structure of the example.

**Comment by dirkschumacher** [comment]
Ok, gone is the `=` operator. I hacked together something last night/this lunch that supports scopes (in the javascript `var` sense, but good enough I think). It can handle these functions:

```R
fun <- armacmp(function(X) {
      x <- X
      y <- 10
      test <- 5 < 10
      if (test) {
        offset <- 20
        y <- offset
      }
      {
        offset <- 40
        y <- offset
      }
      offset <- 30
      y <- offset
      x <- (x %*% 2) + 1
      return(x + y)
    })
```
