### ISSUE TITLE
compile Error

### ISSUE THREAD

**Issue by AugustoSouto** [dirkschumacher/armacmp#86]
Hi, i am trying to run the demo code in R 4.0.0

More specifically, i am trying to run this code:

      trans <- compile(function(X) {return(t(X)) })

I got an error statement asking me the following question:

"compiling c++ code for R requires installation of aditional build tools.
Do you want to install the additional tools now?"

I pressed the "yes" button, but nothing happens.

Any idea of what is wrong? 

Thanks

**Comment by coatless** [comment]
@AugustoSouto need to install compilation tools outside of RStudio. 

Depending on the OS, you either need Rtools if Windows or Xcode CLI if macos.

**Comment by AugustoSouto** [comment]
Thanks. I had an old version of Rtools. The problem was solved when i updated it.
